# Top-level configuration
name = "vms-local"
main = "src/index.ts"
compatibility_date = "2022-07-12"
compatibility_flags = ["nodejs_compat"]

vars = { NODE_ENV = "development", NODE_VERSION = "22.12.0" }

workers_dev = true
keep_vars = true

[[d1_databases]]
binding = "database"
database_name = "vms-local-db"
database_id = "vms-local-db"

# Add KV Namespace here
[[kv_namespaces]]
binding = "KV_STORE"
id = "sessionToken"
preview_id = "test-kv-store" # Enables local KV usage

[env.dev]
name = "vms-dev"

vars = { NODE_ENV = "development", NODE_VERSION = "22.12.0" }

[env.production]
name = "vms"

vars = { NODE_ENV = "production", NODE_VERSION = "22.12.0" }
