# Top-level configuration
name = "vms"
main = "src/index.ts"
compatibility_date = "2022-07-12"
compatibility_flags = ["nodejs_compat"]

vars = { NODE_ENV = "development", NODE_VERSION = "20.18.1" }

workers_dev = true

[env.production]
vars = { NODE_ENV = "production", NODE_VERSION = "20.18.1" }
