# Top-level configuration
name = "vms-dev"
main = "src/index.ts"
compatibility_date = "2022-07-12"
compatibility_flags = ["nodejs_compat"]

vars = { NODE_ENV = "development", NODE_VERSION = "22.12.0" }

workers_dev = true

[env.production]
name = "vms"
vars = { NODE_ENV = "production", NODE_VERSION = "22.12.0" }
